### ISSUE TITLE
zip is corrupted 

### ISSUE THREAD

**Issue by prakashcityzen** [Oreo-onyx/OTA#1]
I am getting zip corrupted message while flashing .What should I do ?

**Comment by YumeMichi** [comment]
Download again and check the sha256sum.
https://github.com/YumeMichi/LineageOTA/blob/master/api.json#L6

**Comment by prakashcityzen** [comment]
I am currently using lineage 14.1 official .Is oxygen os compulsory before flashing?

**Comment by prakashcityzen** [comment]
I am getting error 7 while flashing. I tried the common methods to remove
but again got incorrect zip format.
Its not supporting my one plus x
What should I do now

**Comment by YumeMichi** [comment]
Update your twrp to latest version first

**Comment by YumeMichi** [comment]
https://forum.xda-developers.com/showpost.php?p=77332311&postcount=26

**Comment by prakashcityzen** [comment]
I followed these steps.
what do you mean this
"Wait till it get rebooted and again boot to recovery."
specially "again boot to recovery"
?I boots to system once isn't it ?

**Comment by prakashcityzen** [comment]
Thanks so much it worked
